Single page of todo
Alex-Kalanda/todo-list pull request #10
Opened 2022-04-11 10:16 UTC by Alex-Kalanda

[Single page >>> issue #6](https://github.com/Alex-Kalanda/todo-list/issues/6)

2022-04-11 18:37 UTC, igorTT requested changes

2022-04-11 18:37 UTC, igorTT commented on src/components_common/index.ts
> +import Modal from './Modal/Modal';
Имопртируй из index.js

2022-04-11 18:37 UTC, igorTT commented on src/hooks/useTodoData.ts
> +      });
Перепиши на async/await
Если не придёт data в respnse?

2022-04-11 18:37 UTC, igorTT commented on src/page/TodoPage/TodoPage.tsx
> +  );
Давай это вынесем в отдельный компонент.

2022-04-12 14:15 UTC, igorTT commented on src/components_common/index.ts
> +import Modal from './Modal/Modal';
Да, из index.ts
```javascript
import Modal from './Modal'
export default Modal
```
Во первых чтобы не повторяться в импорте
И потом возможно придётся импортировать что- то допольнительное и этой папки
Например:
```javascript
import Modal from './Modal'
export { useSomeHook } from './hook'
export { someConst } from './constants' 

export default Modal

```
Хотя и у этого подхода есьт противники, но там больше притензия к дефолтному экспорту

2022-04-14 10:30 UTC, Alex-Kalanda commented
Что-то я наплодил бесполезных коммитов и не знаю как старые объединить. Новые понял как --> git  rebase -i HEAD~n

2022-04-14 16:39 UTC, igorTT approved these changes
Потом как поравишь- смерджи сам

2022-04-14 16:39 UTC, igorTT commented on src/hooks/useTodoData.ts
> +};
В try {} catch {} заверни на всякий случай.

2022-04-14 19:39 UTC, merged