Issues/redux
Alex-Kalanda/todo-list pull request #14
Opened 2022-04-18 16:36 UTC by Alex-Kalanda

Добавил редакс на минимальный функционал - то что в мастере было. Всё работает, но меня уже смущают некоторые вещи. Надо глянуть, что глобально не так, потом когда смержится сингл-пэйдж-туду переделаю всё на редакс в отдельной ветке.

2022-04-19 14:07 UTC, igorTT commented
> Добавил редакс на минимальный функционал - то что в мастере было. Всё работает, но меня уже смущают некоторые вещи. Надо глянуть, что глобально не так, потом когда смержится сингл-пэйдж-туду переделаю всё на редакс в отдельной ветке.
Вмерджил, надо конфликты разрезолвить.

2022-04-20 15:37 UTC, Alex-Kalanda commented
Слил мастер в текущую ветку и добавил недостающий функционал

2022-04-20 18:10 UTC, igorTT requested changes
Если зайти на страницу для отдельного todo и перезагрузить- появляется пустые поля
![image](https://user-images.githubusercontent.com/40803254/164295025-2113ec5d-3030-4aeb-9bb6-37ec79489039.png)
Есть предупреждения о недостающих зависимостях в useEffect
Поправь single-page и дальше будем поправлять ещё. Сейчас это как отправная точка.

2022-04-21 17:08 UTC, igorTT requested changes
Нормально. Немного переусложнено, но в целом корректно.

2022-04-21 17:08 UTC, igorTT commented on src/page/TodoPage/TodoPage.tsx
> +  }, [dispatch, id]);
Не знаю- есть ли смысл хранить single todo в редаксе. Его бы тут можно было как локальное состояние сохранить,  Вроде с edit даже конфликтов не вылезет. Попробуй.

2022-04-21 17:08 UTC, igorTT commented on src/redux/reducers/todosReducer.ts
> +      oldTodo.modifiedAt = updTodo?.modifiedAt;
Вот тут ты просто ссылку на объект из массива скопировал и промутировал данные. Скопируй объект.

2022-04-22 11:08 UTC, Alex-Kalanda commented on src/redux/reducers/todosReducer.ts
> +      oldTodo.modifiedAt = updTodo?.modifiedAt;
Так я стейт же не мутирую, а работаю с копией

`const todos_upd = [...state.list] as Todo[];`

`const oldTodo = todos_upd.find(({ id }) => id === updTodo?.id) as Todo;`

2022-04-22 17:10 UTC, igorTT commented on src/redux/reducers/todosReducer.ts
> +      oldTodo.modifiedAt = updTodo?.modifiedAt;
Ты мутируешь объект, который хранится в массиве. Когда ты скопировал массив при помощи rest операторы- ты сделал только поверхностую копию массива. То есть обновил ссылку в памяти для этого массива, но объекты, которые в нём хранятся остались прежние. Потом ты достал из скопированного массива объект и мутировал его поля. 
```javascript
const currentTodo = state.list.find(({ id }) => updTodo.id === id);
const updatedTodo = { ..currentTodo, ...updTodo };
return {
  ...state,
  current: updatedTodo,
  list: [...state.list, updatedTodo].slice(-AMOUNT_DISPLAYED_TODOS),
};
```
Чтобы сохранить порядок записей можно findIndex использовать, скопировать массив и потом просто перезаписать данные с этим индексом в массиве.

2022-04-22 17:21 UTC, igorTT requested changes

2022-04-22 17:21 UTC, igorTT commented on src/page/TodoPage/TodoPage.tsx
> +  }, [currentId, todos.list]);
Вот эту конструкцию вынеси в отдельный хук. Если todos.llist имеется, то нет смысла делать второй запрос.

2022-04-22 17:21 UTC, igorTT commented on src/redux/reducers/todosReducer.ts
> +      oldTodo.modifiedAt = updTodo?.modifiedAt;
Сначала написал, а потом пошёл читать код 👍

2022-04-22 17:39 UTC, Alex-Kalanda commented on src/page/TodoPage/TodoPage.tsx
> +  }, [currentId, todos.list]);
После перезагрузки страницы - todos.list становится пустой, поэтому запрос тут нам нужен

2022-04-25 17:39 UTC, igorTT commented on src/page/TodoPage/TodoPage.tsx
> +  }, [currentId, todos.list]);
Так делай запрос когда он нужен.

2022-04-25 17:42 UTC, igorTT requested changes
При переходе с главной страницы на  single todo- бесконечная загрузка.

2022-04-26 16:27 UTC, igorTT approved these changes

2022-04-26 16:27 UTC, merged