Base app
Alex-Kalanda/todo-list pull request #3
Opened 2022-04-05 19:04 UTC by Alex-Kalanda

#1  base logic
#2 edit fields and todo status

2022-04-06 04:40 UTC, igorTT requested changes
Кнопка 'Cancel' должна закрывать модальное окно.
Есть возможность создания пустых записей после введения пробелов
На макете нету функции редактирования

2022-04-06 08:52 UTC, Alex-Kalanda commented
> Есть возможность создания пустых записей после введения пробелов 
![2022-04-06_11-48-12](https://user-images.githubusercontent.com/74773439/161935839-13a5ce39-11b3-4e46-9939-1ced195435d6.png)
Создаётся же запись с пробелами, что-то другое имелось ввиду?

2022-04-07 17:42 UTC, igorTT commented
> > Есть возможность создания пустых записей после введения пробелов
> 
> Создаётся же запись с пробелами, что-то другое имелось ввиду?
> 
> ![2022-04-06_11-48-12](https://user-images.githubusercontent.com/74773439/161935839-13a5ce39-11b3-4e46-9939-1ced195435d6.png)

Не должна создаваьбся запись с пустыми полями.

2022-04-07 17:43 UTC, igorTT commented
> > На макете нету функции редактирования
> 
> [Твоя ссылка на макет](https://excalidraw.com/#json=OHg7T2-h9dqkUR6em7yHs,eY9yrXaqirnxzsY31zubNw)
> 
> ![2022-04-06_11-53-49](https://user-images.githubusercontent.com/74773439/161937130-53b5585a-bd08-4b8f-953e-ec15f18d7c62.png)
Это ссылка с другого issue

2022-04-07 18:28 UTC, igorTT requested changes

2022-04-07 18:28 UTC, igorTT commented on src/components_common/Modal/Modal.tsx
> +  });
Переусложнено. Просто показывай модально окно по условию в родительском компоненте

2022-04-07 18:28 UTC, igorTT commented on src/components_common/Modal/Modal.tsx
> +    </div>
Если бэкдроп рядом с контентом и не надо будет ловить всплытие события.
Я бы сюда ещё кнопку закрытия засунул.

2022-04-07 18:28 UTC, igorTT commented on src/hooks/useManageMainPage.ts
> +  isLoading: false,
Поменяй значение на true. Убери  action в useEffect
Сравни поведение через debugger

2022-04-07 18:28 UTC, igorTT commented on src/layout/Header/Header.tsx
> +      <h1>{'Todo List'}</h1>
Удали {}

2022-04-07 20:30 UTC, Alex-Kalanda commented on src/components_common/Modal/Modal.tsx
> +  });
ок, это было чисто ради анимации.

2022-04-07 21:34 UTC, Alex-Kalanda commented on src/hooks/useManageMainPage.ts
> +  isLoading: false,
Блин, точно, в промежутке, пока я не поставил isLoading: true в useEffect мелькала начальная карточка, потому что  загрузка false, а массив TODO пока пустой, сейчас всё норм стало

2022-04-08 16:33 UTC, igorTT commented on src/components_common/Modal/Modal.tsx
> +      <div className={styles.background} onClick={() => setActive(false)} />
Этот тоже можно было бы заменить на `onClose`

2022-04-08 16:36 UTC, igorTT approved these changes

2022-04-08 16:36 UTC, merged