Feature todo filter
Alex-Kalanda/todo-list pull request #9
Opened 2022-04-10 11:25 UTC by Alex-Kalanda

#5

2022-04-14 17:10 UTC, igorTT requested changes

2022-04-14 17:10 UTC, igorTT commented on src/hooks/useManageMainPage.ts
> +  displayedTodos: [],
Получил второй источник правды. Попробуй отфильтровать в самом компоненте список + избавишься от одного экшена, не будешь хранить эти данные + вызов в useEffect такой достаточно опасный.
Заодно можешь активный todo- хранить только id и там где-нибудь возле модалки или где ещё понадобится- доставать его из списка. Будет проще прокидывать его, так как простое значение и можно легко мемоизировать и т.п.

2022-04-15 09:08 UTC, Alex-Kalanda commented on src/hooks/useManageMainPage.ts
> +  displayedTodos: [],
> вызов в useEffect такой достаточно опасный

А в чём опасность? Что зависимости от стейта и его же меняем?

2022-04-16 18:15 UTC, igorTT requested changes

2022-04-16 18:15 UTC, igorTT commented on src/page/MainPage/components/form/FormEditTodo.tsx
> +  const { settings, handler } = useComputeForm({ onUpdate, editTodo: editTodo });
```javascript
const { settings, handler } = useComputeForm({ onUpdate, editTodo });
```

2022-04-16 18:15 UTC, igorTT commented on src/page/TodoPage/components/PageContent/Description/Description.tsx
> +      <div className={styles.description}>{data}</div>
div -> p

2022-04-16 18:15 UTC, igorTT commented on src/page/TodoPage/components/PageContent/Title/Title.tsx
> +      <div className={styles.title}>{data}</div>
div -> p

2022-04-16 18:15 UTC, igorTT commented on src/page/MainPage/MainPage.tsx
> +      )}
Вынеси эту логику в отдельный компонент, чтобы там решалось- что показывать и показывать-ли
```javascript
<TodoModal isActiive={isModalActive} onClose={...}  mode={...} todo={...} onUpdate={} onSubmit={}/>
```

2022-04-16 18:15 UTC, igorTT commented on src/hooks/useTodoData.ts
> +    const response: Response = await fetch(`${process.env.REACT_APP_TODO_ENDPOINT}/${id}`);
сохрани `process.env.REACT_APP_TODO_ENDPOINT` в константу и используй

2022-04-17 09:06 UTC, igorTT approved these changes

2022-04-17 09:06 UTC, merged

2022-04-18 14:40 UTC, igorTT commented on src/hooks/useManageMainPage.ts
> +  displayedTodos: [],
> > вызов в useEffect такой достаточно опасный
> 
> А в чём опасность? Что в зависимости от стейта его же и меняем?

Лучше не давай реакту за тебя решать когда проводить такие операции. Если сам вызываешь- это более предсказуемо и понятно.